services:
  nvidia-utils:
    platform: linux/amd64
    build:
      context: .

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    pid: "host"
    restart: always
    ports:
        - ${NVIDIA_PORT:-9988}:8080
        - ${GLANCES_PORT:-61208}:61208
    volumes:
        - ${DATA_PATH}:/experiments:bind
    environment:
        - DATA_PATH=${DATA_PATH}
