services:
  nvidia-utils:
    platform: linux/amd64
    build:
      context: .

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: always
    ports:
        - ${PORT:-9988}:8080
